Retry mac to ip search when libvirt throws an error
Libvirt will return 'Call to virNetworkGetDHCPLeases failed: internal
error: no lease with matching MAC address' when a mac is not found.
fog-libvirt behaviour changed in 0.2.0 but since we immediately start to
poll for an IP, we need to retry despite the libvirt error.

Workaround fix for #668