Poweroff domain on `vagrant halt -f`
`vagrant halt -f` is supposed to poweroff the domain without attempting
graceful shutdown. Before, `vagrant halt -f` was attempting to send
ACPI and waiting for timeout before actually powering off the domain.

Fix a bug where ACPI timeout code would cause an exception to be
thrown, instead of setting :result to false and proceeding to poweroff
the domain.

The before behaviour:

`vagrant halt`:
    - attempt graceful shutdown (/sbin/shutdown)
        ERROR: next action
    - attempt sending ACPI (domain.shutdown)
        ERROR: timeout exception

`vagrant halt -f`:
    - attempt sending ACPI (domain.shutdown)
        ERROR: timeout exception

The after behaviour:

`vagrant halt`:
    - attempt graceful shutdown (/sbin/shutdown)
        ERROR: next action
    - attempt sending ACPI (domain.shutdown)
        ERROR: next action
    - poweroff the machine (domain.poweroff)
        ERROR: hopefully never

`vagrant halt -f`:
    - poweroff the machine (domain.poweroff)
        ERROR: hopefully never